/* Production PortalTrace frontend (module) */
const R = window.PORTALTRACE_RUNTIME || {};
const CONFIG = {
  RPC_ENDPOINT: R.rpcEndpoint || 'wss://rpc.portaldot.io',
  CONTRACT_ADDRESS: R.contractAddress || '',
  CONTRACT_METADATA_URL: R.contractMetadataUrl || '/assets/portaltrace.contract.json',
  TOKEN_SYMBOL: R.tokenSymbol || 'POT'
};

let api=null, contract=null, signer=null, account=null;
const $ = id=>document.getElementById(id);
function showAlert(m){ const c=$('alertContainer'); if(!c) return; const e=document.createElement('div'); e.className='card'; e.style.margin='0.5rem 0'; e.textContent=m; c.prepend(e); setTimeout(()=>e.remove(),6000); }
function short(a){ if(!a) return '—'; a=String(a); return a.length<=12? a : a.slice(0,6)+'…'+a.slice(-4); }

async function initChain(){ if(contract) return; if(!CONFIG.CONTRACT_ADDRESS) throw new Error('Set contractAddress before deploying'); const [{ApiPromise,WsProvider},{ContractPromise}] = await Promise.all([import('https://cdn.jsdelivr.net/npm/@polkadot/api/+esm'), import('https://cdn.jsdelivr.net/npm/@polkadot/api-contract/+esm')]); const meta=await (await fetch(CONFIG.CONTRACT_METADATA_URL)).json(); api = await ApiPromise.create({provider:new WsProvider(CONFIG.RPC_ENDPOINT)}); contract = new ContractPromise(api, meta, CONFIG.CONTRACT_ADDRESS); }

async function connectWallet(){ try{ await initChain(); const ext=await import('https://cdn.jsdelivr.net/npm/@polkadot/extension-dapp/+esm'); await ext.web3Enable('PortalTrace'); const accounts=await ext.web3Accounts(); if(!accounts.length) throw new Error('No accounts'); account=accounts[0].address; const injector=await ext.web3FromAddress(account); signer=injector.signer; localStorage.setItem('portaltrace_account', account); const btn=$('connectWalletBtn'); if(btn) btn.textContent = short(account); showAlert('Wallet connected: '+short(account)); renderProducts(); return true; }catch(e){ showAlert('Wallet error: '+(e.message||e)); console.error(e); return false; } }
function disconnect(){ account=null; signer=null; localStorage.removeItem('portaltrace_account'); $('connectWalletBtn').textContent='Connect Wallet'; showAlert('Wallet disconnected'); }

async function sendTx(method,args=[]){ if(!contract) await initChain(); if(!signer||!account) throw new Error('Connect wallet'); const tx = contract.tx[method]({ gasLimit:-1, storageDepositLimit:null }, ...args); return new Promise((res,rej)=>{ tx.signAndSend(account,{signer},result=>{ if(result.dispatchError) rej(result.dispatchError.toString()); if(result.status.isInBlock||result.status.isFinalized) res(result); }).catch(rej); }); }

async function getNextId(){ const r = await contract.query.get_next_product_id(account||CONFIG.CONTRACT_ADDRESS,{gasLimit:-1,storageDepositLimit:null}); return Number(r.output?.toString()||0); }
async function getProduct(id){ const r = await contract.query.get_product(account||CONFIG.CONTRACT_ADDRESS,{gasLimit:-1,storageDepositLimit:null},Number(id)); const out = typeof r.output?.toJSON==='function'? r.output.toJSON() : r.output; const raw = out?.Ok || out; if(!raw) return null; return { id:Number(raw.id||id), name:raw.name||'', manufacturer:raw.manufacturer||'', origin:raw.origin||'', ipfs_hash:raw.ipfs_hash||raw.ipfsHash||'', owner:raw.owner||'', verified:!!raw.verified }; }

async function renderProducts(){ const c=$('productsContainer'); if(!c) return; c.innerHTML='Loading…'; try{ await initChain(); const next=await getNextId(); if(!next){ c.innerHTML='<p style="color:#9aa4b2">No on-chain products</p>'; return;} const items=[]; for(let i=Math.max(1,next-6); i<next; i++){ const p = await getProduct(i); if(p) items.push(p); } if(!items.length){ c.innerHTML='<p style="color:#9aa4b2">No on-chain products</p>'; return;} c.innerHTML=items.reverse().map(p=>`<div class="product-card"><strong>${escapeHtml(p.name)}</strong><div style="color:#9aa4b2;font-size:.9rem">ID: ${p.id}</div><div style="margin-top:.5rem;color:#9aa4b2">${escapeHtml(p.manufacturer)} · ${escapeHtml(p.origin)}</div><div style="margin-top:.65rem;display:flex;gap:.5rem"><button class="btn btn-secondary" onclick="quickVerify(${p.id})">Verify</button><a class="btn btn-outline" href='verify.html?product=${p.id}'>View</a></div></div>`).join(''); }catch(e){ c.innerHTML='<p style="color:#9aa4b2">Failed to load</p>'; console.error(e);} }

function renderOwnershipHistory(productId){ const c=$('ownershipHistory'); if(!c) return; c.innerHTML = `<div class="card"><p>No ownership history stored in the current contract.</p><p style="color:#9aa4b2;font-size:.9rem">This page can verify product data on-chain, but ownership history requires a contract that emits or stores transfer history.</p></div>`; }

async function displayProductDetails(product){ if(!product) return; const detailsSection=$('detailsSection'); const featuresSection=$('featuresSection'); if(featuresSection) featuresSection.style.display='none'; if(detailsSection) detailsSection.style.display='block'; const set=(id,val)=>{ const el=$(id); if(el) el.textContent = val; }; set('detailsName', product.name || ''); set('detailsId', 'Product ID: '+product.id); set('detailsManufacturer', product.manufacturer || ''); set('detailsOrigin', product.origin || ''); set('detailsIpfs', product.ipfs_hash || ''); set('detailsOwner', product.owner || ''); const badge=$('verificationBadge'); const verifyStatus=$('verifyStatus'); const verifyIcon=$('verifyIcon'); if(product.verified){ if(badge){ badge.className='badge badge-verified'; badge.textContent='✓ Verified'; } if(verifyStatus) verifyStatus.textContent='Verified'; if(verifyIcon) verifyIcon.textContent='✓'; } else { if(badge){ badge.className='badge badge-pending'; badge.textContent='⏱ Pending Verification'; } if(verifyStatus) verifyStatus.textContent='Pending'; if(verifyIcon) verifyIcon.textContent='⏱'; } if($('ownershipHistory')) renderOwnershipHistory(product.id); }

function generateSimpleQRCode(text, canvasId){ const canvas=$(canvasId); if(!canvas) return; const ctx=canvas.getContext('2d'); const size=240; canvas.width=size; canvas.height=size; ctx.fillStyle='#fff'; ctx.fillRect(0,0,size,size); ctx.fillStyle='#000'; let hash=0; for(let i=0;i<text.length;i++) hash=((hash<<5)-hash)+text.charCodeAt(i); const cell=12; for(let y=0;y<size;y+=cell){ for(let x=0;x<size;x+=cell){ const n=Math.abs(((hash+x*73856093)^(y*19349663)))%2; if(n===0) ctx.fillRect(x,y,cell,cell); } } }

async function verifyProductById(id){ try{ const p = await getProduct(id); if(!p) throw new Error('Product not found'); generateSimpleQRCode(String(id), 'qrCode'); await displayProductDetails(p); showAlert('Product verified locally from chain data'); return p; }catch(e){ showAlert('Verify failed: '+(e.message||e)); console.error(e); return null; } }

function escapeHtml(s){ if(!s) return ''; return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]); }

function setup(){ const btn=$('connectWalletBtn'); if(btn) btn.onclick = async ()=> account? disconnect() : await connectWallet(); const reg=$('registerForm'); if(reg) reg.onsubmit = async e=>{ e.preventDefault(); const name=$('productName').value.trim(); const m=$('manufacturer').value.trim(); const o=$('origin').value.trim(); const ip=$('ipfsHash').value.trim()||generateIPFSHash(); if(!name||!m||!o) { showAlert('Fill required fields'); return; } try{ await sendTx('create_product',[name,m,o,ip]); showAlert('Register tx sent'); setTimeout(()=>renderProducts(),2500); reg.reset(); }catch(err){ console.error(err); showAlert('Register failed: '+(err.message||err)); } } }

window.quickVerify = async function(id){ try{ await sendTx('verify_product',[Number(id)]); showAlert('Verify tx sent'); setTimeout(()=>renderProducts(),2000);}catch(e){ console.error(e); showAlert('Verify failed: '+(e.message||e)); } };

function generateIPFSHash(){ const chars='0123456789abcdefghijklmnopqrstuvwxyz'; let h='Qm'; for(let i=0;i<44;i++) h+=chars.charAt(Math.floor(Math.random()*chars.length)); return h; }

document.addEventListener('DOMContentLoaded', async ()=>{ const saved=localStorage.getItem('portaltrace_account'); const btn=$('connectWalletBtn'); if(saved && btn){ btn.textContent = short(saved); account = saved; } setup(); try{ await initChain(); }catch(e){ console.warn('initChain',e)} renderProducts(); const params = new URLSearchParams(window.location.search); const productId = params.get('product'); if($('verifyForm')){ $('verifyForm').addEventListener('submit', async e=>{ e.preventDefault(); const id = Number($('productId').value); if(!id){ showAlert('Enter product ID'); return; } await verifyProductById(id); }); if(productId){ $('productId').value = productId; verifyProductById(Number(productId)); } } });
